
------------------------------------------

SELECT STARNAME
FROM STARSIN, MOVIESTAR
WHERE MOVIETITLE='The Usual Suspects' AND 
MOVIESTAR.NAME=STARSIN.STARNAME AND
MOVIESTAR.GENDER='M'

------------------------------------------

SELECT STARNAME
FROM STARSIN, MOVIE
WHERE MOVIEYEAR=1995 AND 
STARSIN.MOVIETITLE=MOVIE.TITLE
AND MOVIE.STUDIONAME='MGM'

------------------------------------------

SELECT DISTINCT MOVIEEXEC.NAME
FROM MOVIEEXEC, STUDIO, MOVIE
WHERE STUDIO.NAME='MGM' AND
MOVIE.STUDIONAME = STUDIO.NAME AND
MOVIE.PRODUCERC#=MOVIEEXEC.CERT#

------------------------------------------

SELECT TITLE
FROM MOVIE
WHERE LENGTH > (SELECT LENGTH FROM MOVIE WHERE TITLE='Star Wars')

------------------------------------------

SELECT NAME
FROM MOVIEEXEC
WHERE NETWORTH > (SELECT NETWORTH FROM MOVIEEXEC WHERE NAME='Stephen Spielberg')
