
------------------------------------------

SELECT DISTINCT NAME
FROM SHIPS, CLASSES
WHERE SHIPS.CLASS=CLASSES.CLASS AND
CLASSES.DISPLACEMENT >= 50000

------------------------------------------

SELECT SHIPS.NAME, CLASSES.DISPLACEMENT, CLASSES.NUMGUNS
FROM SHIPS, CLASSES, BATTLES, OUTCOMES
WHERE SHIPS.CLASS=CLASSES.CLASS AND
BATTLES.NAME='Guadalcanal' AND
OUTCOMES.SHIP=SHIPS.NAME AND
OUTCOMES.BATTLE=BATTLES.NAME

------------------------------------------

SELECT DISTINCT CLASSES.COUNTRY
FROM SHIPS, CLASSES
WHERE CLASSES.TYPE='bb' AND
SHIPS.CLASS=CLASSES.CLASS
INTERSECT
SELECT DISTINCT CLASSES.COUNTRY
FROM SHIPS, CLASSES
WHERE CLASSES.TYPE='bc' AND
SHIPS.CLASS=CLASSES.CLASS

------------------------------------------

SELECT SHIPS.NAME
FROM SHIPS, BATTLES AS B1, BATTLES AS B2,
OUTCOMES AS O1, OUTCOMES AS O2
WHERE SHIPS.NAME=O1.SHIP AND
SHIPS.NAME=O2.SHIP AND
B1.NAME=O1.BATTLE AND
B2.NAME=O2.BATTLE AND
B1.DATE<B2.DATE AND
O1.RESULT='damaged'