INSERT INTO MOVIESTAR(NAME, ADDRESS, GENDER, BIRTHDATE)
VALUES('Nicole Kidman', NULL, NULL, 1967-06-20)

DELETE FROM MOVIEEXEC
WHERE NETWORTH>30000000

DELETE FROM MOVIESTAR
WHERE ADDRESS IS NULL
