SELECT *
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS

SELECT *
FROM SHIPS RIGHT JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS

SELECT CLASSES.COUNTRY, SHIPS.NAME
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS
LEFT JOIN OUTCOMES ON SHIPS.NAME=OUTCOMES.SHIP
WHERE OUTCOMES.BATTLE IS NULL
ORDER BY CLASSES.COUNTRY, SHIPS.NAME

SELECT SHIPS.NAME AS 'Ship Name'
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS
WHERE SHIPS.LAUNCHED=1916 AND CLASSES.NUMGUNS>=7

SELECT SHIPS.NAME, BATTLES.NAME, BATTLES.DATE
FROM SHIPS JOIN OUTCOMES ON SHIPS.NAME=OUTCOMES.SHIP
JOIN BATTLES ON OUTCOMES.BATTLE=BATTLES.NAME
WHERE OUTCOMES.RESULT='sunk'
ORDER BY BATTLES.NAME

SELECT SHIPS.NAME, CLASSES.DISPLACEMENT, SHIPS.LAUNCHED
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS
WHERE SHIPS.NAME=SHIPS.CLASS

SELECT CLASSES.CLASS, CLASSES.TYPE, CLASSES.COUNTRY, CLASSES.NUMGUNS,
CLASSES.BORE, CLASSES.DISPLACEMENT
FROM SHIPS RIGHT JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS
WHERE SHIPS.NAME IS NULL

SELECT SHIPS.NAME, CLASSES.DISPLACEMENT, CLASSES.NUMGUNS, OUTCOMES.RESULT
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS
JOIN OUTCOMES ON SHIPS.NAME=OUTCOMES.SHIP
WHERE OUTCOMES.BATTLE='North Atlantic'