SELECT PRODUCT.maker, PRODUCT.model, PRODUCT.type
FROM PRODUCT LEFT JOIN ((SELECT PC.code, PC.model FROM PC) UNION
(SELECT LAPTOP.code, LAPTOP.model FROM LAPTOP) UNION
(SELECT PRINTER.code, PRINTER.model FROM PRINTER)) AS T
ON PRODUCT.model = T.model
WHERE T.code IS NULL

SELECT DISTINCT PRODUCT.maker
FROM PRODUCT JOIN PRINTER ON PRODUCT.model=PRINTER.model
INTERSECT
SELECT DISTINCT PRODUCT.maker
FROM PRODUCT JOIN LAPTOP ON PRODUCT.model=LAPTOP.model

SELECT DISTINCT L1.hd
FROM LAPTOP AS L1 CROSS JOIN LAPTOP AS L2
WHERE L1.model!=L2.model AND L1.hd=L2.hd

SELECT PC.code, PC.model, PC.speed,
PC.ram, PC.hd, PC.cd, PC.price
FROM PC LEFT JOIN PRODUCT ON PC.model=PRODUCT.model
WHERE PRODUCT.model IS NULL