SELECT MOVIE.TITLE, MOVIEEXEC.NAME
FROM MOVIE JOIN MOVIEEXEC ON MOVIE.PRODUCERC#=MOVIEEXEC.CERT#
WHERE MOVIE.PRODUCERC# = (SELECT MOVIE.PRODUCERC# 
FROM MOVIE 
WHERE MOVIE.TITLE='Star Wars'); 

SELECT DISTINCT MOVIEEXEC.NAME
FROM STARSIN JOIN MOVIE ON STARSIN.MOVIETITLE=MOVIE.TITLE
JOIN MOVIEEXEC ON MOVIE.PRODUCERC#=MOVIEEXEC.CERT#
WHERE STARSIN.STARNAME='Harrison Ford'

SELECT DISTINCT STUDIO.NAME, STARSIN.STARNAME
FROM STUDIO JOIN MOVIE ON STUDIO.NAME=MOVIE.STUDIONAME
JOIN STARSIN ON MOVIE.TITLE=STARSIN.MOVIETITLE
ORDER BY STUDIO.NAME

SELECT DISTINCT MOVIESTAR.NAME
FROM MOVIESTAR JOIN STARSIN ON MOVIESTAR.NAME=STARSIN.STARNAME
JOIN MOVIE ON MOVIE.TITLE=STARSIN.MOVIETITLE
JOIN MOVIEEXEC ON MOVIE.PRODUCERC#=MOVIEEXEC.CERT#
WHERE MOVIEEXEC.NETWORTH>=ALL(SELECT NETWORTH FROM MOVIEEXEC)

SELECT MOVIESTAR.NAME, STARSIN.MOVIETITLE
FROM MOVIESTAR LEFT JOIN STARSIN ON MOVIESTAR.NAME=STARSIN.STARNAME
WHERE STARSIN.MOVIETITLE IS NULL