SELECT DISTINCT CLASSES.COUNTRY
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS
WHERE CLASSES.NUMGUNS>=ALL(SELECT NUMGUNS FROM CLASSES)

SELECT CLASS
FROM CLASSES 
WHERE CLASS IN
(SELECT CLASS FROM SHIPS JOIN OUTCOMES ON SHIPS.NAME=OUTCOMES.SHIP AND
OUTCOMES.RESULT='sunk')

SELECT NAME, SHIPS.CLASS
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS
WHERE CLASSES.BORE=16

SELECT OUTCOMES.BATTLE
FROM OUTCOMES JOIN SHIPS ON OUTCOMES.SHIP=SHIPS.NAME
WHERE SHIPS.CLASS='Kongo'

SELECT SHIPS.CLASS, SHIPS.NAME
FROM SHIPS JOIN CLASSES AS C1 ON SHIPS.CLASS=C1.CLASS
WHERE C1.NUMGUNS>=ALL(SELECT C2.NUMGUNS
FROM SHIPS JOIN CLASSES AS C2 ON SHIPS.CLASS=C2.CLASS
WHERE C1.BORE=C2.BORE)