SELECT DISTINCT MAKER
FROM PC JOIN PRODUCT ON PC.MODEL=PRODUCT.MODEL
WHERE SPEED > 500

SELECT CODE, MODEL, PRICE
FROM PRINTER
WHERE PRICE >= ALL(SELECT PRICE FROM PRINTER)

SELECT *
FROM LAPTOP
WHERE LAPTOP.SPEED < ALL(SELECT SPEED FROM PC)

SELECT TBL.MODEL, TBL.PRICE
FROM ((SELECT MODEL, PRICE FROM PC) UNION
(SELECT MODEL, PRICE FROM PRINTER) UNION
(SELECT MODEL, PRICE FROM LAPTOP)) AS TBL
WHERE TBL.PRICE>=ALL(SELECT PRICE FROM ((SELECT MODEL, PRICE FROM PC)
UNION (SELECT MODEL, PRICE FROM PRINTER) UNION
(SELECT MODEL, PRICE FROM LAPTOP)) AS TBL2)

SELECT MAKER
FROM PRINTER JOIN PRODUCT ON PRINTER.MODEL=PRODUCT.MODEL
WHERE COLOR='y' AND PRINTER.PRICE<=ALL(SELECT PRICE FROM PRINTER WHERE COLOR='y')
