SELECT MOVIESTAR.NAME
FROM MOVIESTAR
WHERE GENDER='F' AND
MOVIESTAR.NAME IN
(SELECT MOVIEEXEC.NAME FROM MOVIEEXEC
WHERE NETWORTH>10000000)

SELECT MOVIESTAR.NAME
FROM MOVIESTAR
WHERE MOVIESTAR.NAME NOT IN
(SELECT MOVIEEXEC.NAME FROM MOVIEEXEC)

SELECT TITLE
FROM MOVIE
WHERE LENGTH > (SELECT LENGTH FROM MOVIE
WHERE TITLE='Star Wars')

SELECT MOVIE.TITLE, MOVIEEXEC.NAME
FROM MOVIE JOIN MOVIEEXEC ON MOVIE.PRODUCERC#=MOVIEEXEC.CERT#
WHERE MOVIEEXEC.NETWORTH > (SELECT NETWORTH FROM MOVIEEXEC 
WHERE NAME='Merv Griffin')
