SELECT TITLE, YEAR, LENGTH
FROM MOVIE
WHERE LENGTH>=120 OR LENGTH IS NULL AND YEAR<2000

SELECT NAME, GENDER
FROM MOVIESTAR
WHERE NAME LIKE 'J%'
ORDER BY NAME DESC

SELECT MOVIE.STUDIONAME, COUNT(DISTINCT STARSIN.STARNAME) AS NUM_ACTORS
FROM MOVIE JOIN STARSIN ON MOVIE.TITLE=STARSIN.MOVIETITLE
GROUP BY MOVIE.STUDIONAME

SELECT MOVIESTAR.NAME, COUNT(STARSIN.MOVIETITLE) AS NUM_MOVIES
FROM MOVIESTAR LEFT JOIN STARSIN ON MOVIESTAR.NAME=STARSIN.STARNAME
GROUP BY MOVIESTAR.NAME

SELECT STUDIO.NAME, MOVIE.TITLE, MOVIE.YEAR
FROM STUDIO JOIN MOVIE ON STUDIO.NAME=MOVIE.STUDIONAME
WHERE MOVIE.YEAR>=ALL(SELECT YEAR FROM MOVIE WHERE STUDIONAME=STUDIO.NAME)

SELECT TOP 1 NAME
FROM MOVIESTAR
WHERE GENDER='M'
ORDER BY BIRTHDATE

SELECT MOVIE.STUDIONAME, STARSIN.STARNAME, COUNT(MOVIE.TITLE) AS MOVIE_COUNT
FROM STARSIN JOIN MOVIE ON STARSIN.MOVIETITLE=MOVIE.TITLE
GROUP BY MOVIE.STUDIONAME, STARSIN.STARNAME
HAVING COUNT(MOVIE.TITLE)>=ALL(SELECT COUNT(MOVIE.TITLE)
FROM STARSIN JOIN MOVIE ON STARSIN.MOVIETITLE=MOVIE.TITLE
GROUP BY MOVIE.STUDIONAME, STARSIN.STARNAME
)

SELECT MOVIE.TITLE, MOVIE.YEAR, COUNT(STARSIN.STARNAME) AS NUM_ACTORS
FROM MOVIE JOIN STARSIN ON MOVIE.TITLE=STARSIN.MOVIETITLE
GROUP BY MOVIE.TITLE, MOVIE.YEAR
HAVING COUNT(STARSIN.STARNAME)>2