SELECT DISTINCT SHIP
FROM OUTCOMES
WHERE SHIP LIKE 'C%' OR SHIP LIKE 'K%'

SELECT DISTINCT SHIPS.NAME, CLASSES.COUNTRY
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS
LEFT JOIN OUTCOMES ON SHIPS.NAME=OUTCOMES.SHIP
WHERE OUTCOMES.RESULT IS NULL OR OUTCOMES.RESULT != 'sunk' 

SELECT CLASSES.COUNTRY, COUNT(SHIP)
FROM CLASSES LEFT JOIN SHIPS ON CLASSES.CLASS=SHIPS.CLASS
LEFT JOIN OUTCOMES ON OUTCOMES.SHIP=SHIPS.NAME
WHERE OUTCOMES.RESULT IS NULL OR OUTCOMES.RESULT = 'sunk'
GROUP BY CLASSES.COUNTRY

SELECT BATTLES.NAME
FROM BATTLES JOIN OUTCOMES ON OUTCOMES.BATTLE=BATTLES.NAME
GROUP BY BATTLES.NAME
HAVING COUNT(OUTCOMES.SHIP)>(SELECT COUNT(OUTCOMES.SHIP)
FROM OUTCOMES
WHERE OUTCOMES.BATTLE='Guadalcanal')

SELECT OUTCOMES.BATTLE
FROM OUTCOMES JOIN SHIPS ON OUTCOMES.SHIP=SHIPS.NAME 
JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS
GROUP BY OUTCOMES.BATTLE
HAVING COUNT(DISTINCT COUNTRY)>
(SELECT COUNT(DISTINCT COUNTRY)
FROM OUTCOMES JOIN SHIPS ON OUTCOMES.SHIP=SHIPS.NAME 
JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS
GROUP BY OUTCOMES.BATTLE
HAVING OUTCOMES.BATTLE='Surigao Strait'
)

SELECT COUNT(*)
FROM (OUTCOMES AS O1 JOIN BATTLES AS B1 ON O1.BATTLE=B1.NAME)
CROSS JOIN 
(OUTCOMES AS O2 JOIN BATTLES AS B2 ON O2.BATTLE=B2.NAME)
WHERE B1.DATE<B2.DATE AND O1.RESULT='damaged' AND O2.RESULT='ok'
AND O1.SHIP=O2.SHIP

SELECT O1.SHIP
FROM (SHIPS AS S1 JOIN OUTCOMES AS O1 ON S1.NAME=O1.SHIP JOIN BATTLES AS B1 ON O1.BATTLE=B1.NAME)
CROSS JOIN
(SHIPS AS S2 JOIN OUTCOMES AS O2 ON S2.NAME=O2.SHIP JOIN BATTLES AS B2 ON O2.BATTLE=B2.NAME)
WHERE S1.NAME=S2.NAME AND B1.DATE<B2.DATE AND
(SELECT COUNT(OUTCOMES.SHIP)
FROM OUTCOMES
GROUP BY OUTCOMES.BATTLE
HAVING OUTCOMES.BATTLE=B1.NAME
)
<
(SELECT COUNT(OUTCOMES.SHIP)
FROM OUTCOMES
GROUP BY OUTCOMES.BATTLE
HAVING OUTCOMES.BATTLE=B2.NAME
)