SELECT COUNT(CLASS)
FROM CLASSES
WHERE TYPE='bb'

SELECT CLASS, NUMGUNS
FROM CLASSES
WHERE TYPE='bb'

SELECT AVG(NUMGUNS)
FROM CLASSES
WHERE TYPE='bb'

SELECT CLASSES.CLASS, MIN(SHIPS.LAUNCHED) AS FIRST_YEAR, MAX(SHIPS.LAUNCHED) AS LAST_YEAR
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS
GROUP BY CLASSES.CLASS

SELECT CLASSES.CLASS, COUNT(SHIPS.NAME)
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS JOIN OUTCOMES ON SHIPS.NAME=OUTCOMES.SHIP
WHERE OUTCOMES.RESULT='sunk'
GROUP BY CLASSES.CLASS

SELECT CLASSES.CLASS, COUNT(SHIPS.NAME)
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS JOIN OUTCOMES ON SHIPS.NAME=OUTCOMES.SHIP
WHERE OUTCOMES.RESULT='sunk'
GROUP BY CLASSES.CLASS
HAVING CLASSES.CLASS IN (SELECT CLASSES.CLASS FROM CLASSES JOIN SHIPS ON CLASSES.CLASS=SHIPS.CLASS GROUP BY CLASSES.CLASS HAVING COUNT(SHIPS.NAME) > 2)

SELECT CLASSES.COUNTRY, CONVERT(DECIMAL(9,2), AVG(CLASSES.BORE))
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS
GROUP BY CLASSES.COUNTRY